export type GoalCategory = 'career' | 'business' | 'health' | 'learning' | 'finance' | 'personal_growth';
export type SkillLevel = 'beginner' | 'intermediate' | 'advanced';
export type EducationLevel = 'school_student' | 'college_student' | 'graduate' | 'professional';

export interface UserProfile {
  isOnboarded: boolean;
  fullName: string;
  age: number;
  gender: string;
  country: string;
  occupation: string;
  education: EducationLevel;
  lifeGoals: GoalCategory[];
  availableTime: number; // Daily hours
  interests: string[];
  skillLevel: SkillLevel;
  
  // XP & Gamification
  xp: number;
  level: number;
  
  // Key Life Scores (generated by AI and recalculated based on active items)
  scores: {
    growth: number;
    productivity: number;
    learning: number;
    health: number;
    goal: number;
    balanceIndex: number;
  };
  
  aiProfileAnalysis?: string;
  createdAt: string;
}

export interface Milestone {
  id: string;
  title: string;
  done: boolean;
  targetWeek: string;
}

export interface Goal {
  id: string;
  title: string;
  category: GoalCategory;
  description: string;
  status: 'active' | 'completed' | 'on_hold';
  targetDate: string;
  milestones: Milestone[];
  monthlyPlan?: string;
  weeklyPlan?: string;
  dailyTasks?: string[];
  successProbability?: number; // Calculated success meter
  collisionWarnings?: string[]; // Detected during layout
  createdAt: string;
}

export interface RoadmapStep {
  id: string;
  title: string;
  done: boolean;
}

export interface RoadmapStage {
  title: string;
  steps: RoadmapStep[];
}

export interface Roadmap {
  id: string;
  goalId: string;
  title: string;
  stages: RoadmapStage[];
  activeStageIndex: number;
  createdAt: string;
}

export interface Habit {
  id: string;
  name: string;
  category: 'study' | 'exercise' | 'reading' | 'sleep' | 'meditation' | 'water' | 'custom';
  streak: number;
  maxStreak: number;
  logs: Record<string, boolean>; // Key is YYYY-MM-DD
  frequency: 'daily' | 'weekly';
}

export interface Task {
  id: string;
  title: string;
  completed: boolean;
  priority: 'high' | 'medium' | 'low';
  date: string; // YYYY-MM-DD
  timeBlock?: string; // e.g. "09:00 - 11:00"
  xpAwarded?: boolean;
}

export interface FocusBlock {
  id: string;
  title: string;
  startTime: string; // HH:MM
  duration: number; // minutes
  category: 'work' | 'study' | 'fitness' | 'learning' | 'rest';
  completed: boolean;
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  category: 'goals' | 'streaks' | 'tasks' | 'general';
  xpAwarded: number;
  icon: string; // Lucide icon name
  unlocked: boolean;
  unlockedAt?: string;
}

export interface Badge {
  id: string;
  title: string;
  description: string;
  category: 'productivity' | 'learning' | 'consistency' | 'customization';
  unlocked: boolean;
  imageUrl?: string;
}

export interface AIRecommendation {
  id: string;
  category: 'schedule' | 'habit' | 'learning' | 'routine';
  text: string;
}

export interface FutureProjection {
  productivityGain: number; // % improvement in 6 months
  growthMultiplier: number; // e.g. 1.3x
  healthOutlook: string;
  learningMilestonesCount: number;
  simulationReport: string;
  analyzedAt: string;
}

export interface DecisionOption {
  optionA: string;
  optionB: string;
  prosA: string[];
  consA: string[];
  prosB: string[];
  consB: string[];
  marketDemandA: string;
  marketDemandB: string;
  growthPotentialA: string;
  growthPotentialB: string;
  verdict: string;
}

export interface CollisionCheckResult {
  conflicted: boolean;
  warnings: string[];
  impactScore: number; // 0-100 indicating risk
  adviceList: string[];
}
